context:
  name: tinytag
  version: "2.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 564e573e308d9fa78432493b4987fca1f84fb1f2ce29c586fc54629155e4fca0

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core >=3.2
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - tinytag
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/tinytag/tinytag
  summary: Python library for reading audio file metadata
  description: |
    tinytag is a Python library for reading audio file metadata
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/tinytag/tinytag
  repository: https://github.com/tinytag/tinytag

extra:
  recipe-maintainers:
    - pavelzw
